when:
  - event: [push, manual]
    branch: [master]

steps:
  - name: Build and Publish
    image: maven:4.0.0-rc-5-eclipse-temurin-21
    privileged: false
    failure: fail
    commands:
      - mkdir -p /root/.m2
      - |
        cat <<EOF > /root/.m2/settings.xml
        <settings>
          <servers>
            <server>
              <id>gamecrash-git</id>
              <username>$OWNER</username>
              <password>$TOKEN</password>
            </server>
          </servers>
        </settings>
        EOF
      - mvn clean package javadoc:jar deploy -DksipTests
    environment:
      OWNER:
        from_secret: reg_owner
      TOKEN:
        from_secret: reg_token